{
 "title": "Patroni [bitte-cells]",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Patroni Timeline Counter",
   "type": "graph",
   "description": "Postgres timeline of this node (if running), 0 otherwise.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "patroni_postgres_timeline{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Cluster Unlock Status",
   "type": "graph",
   "description": "Value is 1 if the cluster is unlocked, 0 if locked.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "patroni_cluster_unlocked{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Postgres Running",
   "type": "graph",
   "description": "Value is 1 if Postgres is running, 0 otherwise.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "patroni_postgres_running{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Master",
   "type": "graph",
   "description": "Value is 1 if this node is the leader, 0 otherwise.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "patroni_master{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Replica",
   "type": "graph",
   "description": "Value is 1 if this node is a replica, 0 otherwise.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_replica{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Standby Leader",
   "type": "graph",
   "description": "Value is 1 if this node is the standby_leader, 0 otherwise.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_standby_leader{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Postmaster Start Time",
   "type": "graph",
   "description": "Epoch seconds since Postgres started.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_postmaster_start_time{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Postgres Server Version",
   "type": "graph",
   "description": "Version of Postgres (if running), 0 otherwise.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_postgres_server_version{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Xlog Location",
   "type": "graph",
   "description": "Current location of the Postgres transaction log, 0 if this node is not the leader.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_location{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Xlog Replayed Location",
   "type": "graph",
   "description": "Current location of the replayed Postgres transaction log, 0 if this node is not a replica.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_replayed_location{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Xlog Received Location",
   "type": "graph",
   "description": "Current location of the received Postgres transaction log, 0 if this node is not a replica.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_received_location{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Xlog Replayed Timestamp",
   "type": "graph",
   "description": "Current timestamp of the replayed Postgres transaction log, 0 if null.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_replayed_timestamp{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni Xlog Paused",
   "type": "graph",
   "description": "Value is 1 if the Postgres xlog is paused, 0 otherwise.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_paused{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Patroni DCS Last Seen Timestamp",
   "type": "graph",
   "description": "Epoch timestamp when DCS was last contacted successfully.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_dcs_last_seen{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  }
 ]
}