{
 "title": "Vault [bitte]",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "barrier.delete",
   "type": "graph",
   "description": "Duration of time taken by DELETE operations at the barrier",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(vault_barrier_delete_count[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "barrier.get",
   "type": "graph",
   "description": "Duration of time taken by GET operations at the barrier",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(vault_barrier_get_count[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "barrier.put",
   "type": "graph",
   "description": "Duration of time taken by PUT operations at the barrier",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(vault_barrier_put_count[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "barrier.list",
   "type": "graph",
   "description": "Duration of time taken by LIST operations at the barrier",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(vault_barrier_list_count[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "core.check_token",
   "type": "graph",
   "description": "Duration of time taken by token checks handled by Vault core",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "vault_core_check_token_count", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "core.fetch_acl_and_token",
   "type": "graph",
   "description": "Duration of time taken by ACL and corresponding token entry fetches handled by Vault core",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_fetch_acl_and_token_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "core.handle_login_request",
   "type": "graph",
   "description": "Duration of time taken by login requests handled by Vault core",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_handle_login_request_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "core.handle_request",
   "type": "graph",
   "description": "Duration of time taken by requests handled by Vault core",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_handle_request_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "core.leadership_setup_failed",
   "type": "graph",
   "description": "Duration of time taken by cluster leadership setup failures which have occurred in a highly available Vault cluster. This should be monitored and alerted on for overall cluster leadership status.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_leadership_setup_failed_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "core.leadership_lost",
   "type": "graph",
   "description": "Duration of time taken by cluster leadership losses which have occurred in a highly available Vault cluster. This should be monitored and alerted on for overall cluster leadership status.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vault_core_leadership_lost_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "core.pre_seal",
   "type": "graph",
   "description": "Duration of time taken by post-unseal operations handled by Vault core",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "vault_core_pre_seal_count", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "core.post_unseal",
   "type": "graph",
   "description": "Duration of time taken by post-unseal operations handled by Vault core",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "vault_core_post_unseal_count", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "core.unsealed",
   "type": "graph",
   "description": "Has value 1 when Vault is unsealed, and 0 when Vault is sealed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "vault_core_unsealed_value", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "core.unseal",
   "type": "graph",
   "description": "Duration of time taken by unseal operations",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "vault_core_unseal_count", "legendFormat": "{{host}}" }
   ]
  }
 ]
}