{
 "title": "Tempo Operational",
 "tags": [ "tempo" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Tempo Systemd Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"tempo\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"tempo\"}"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"tempo\"}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "gcs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=\"tempo\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "go heap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"tempo\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"tempo\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"tempo\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"tempo\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "tx/rx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(tempo_ingester_bytes_received_total{job=\"tempo\"}[$__rate_interval])",
     "legendFormat": "rx-{{pod}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$component.*\"}[$__rate_interval])",
     "legendFormat": "tx-{{pod}}"
    }
   ]
  },
  { "title": "Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "%age total work queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "tempodb_work_queue_length{job=\"tempo\"} / tempodb_work_queue_max{job=\"tempo\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "maintenance errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(tempodb_compaction_errors_total{job=\"tempo\"}[$__rate_interval])",
     "legendFormat": "compaction_err"
    },
    {
     "expr": "increase(tempodb_retention_errors_total{job=\"tempo\"}[$__rate_interval])",
     "legendFormat": "retention_err"
    },
    {
     "expr": "increase(tempodb_blocklist_poll_errors_total{job=\"tempo\"}[$__rate_interval])",
     "legendFormat": "blocklist_err"
    }
   ]
  },
  {
   "title": "Blocklist Poll Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Blocklist Length",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempodb_blocklist_length{ job=\"tempo\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "retention duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_retention_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_retention_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_retention_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "retention",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempodb_retention_deleted_total{job=\"tempo\"}[$__rate_interval]))",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(increase(tempodb_retention_marked_for_deletion_total{job=\"tempo\"}[$__rate_interval]))",
     "legendFormat": "marked_for_deletion"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Queries/Sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\".*api_traces_traceid\", job=\"tempo\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Search Queries/Sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\".*api_search.*\", job=\"tempo\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Search Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Queries/Sec (Querier)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"querier_.*api_traces_traceid\",job=\"tempo\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Query Latency (Querier)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Search Queries/Sec (Querier)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"querier_.*api_search.*\", cluster=\"$cluster\", namespace=\"$namespace\", job=\"$namespace/querier\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Search Query Latency (Querier)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Queries/Sec (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=\"/tempopb.Querier/FindTraceByID\", job=\"tempo\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Query Latency (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Search Queries/Sec (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"/tempopb.Querier/Search.*\", job=\"tempo\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Search Query Latency (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5",
     "stepMode": "min"
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Spans Received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tempo_distributor_spans_received_total{job=\"tempo\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Traces Created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(tempo_ingester_traces_created_total{job=\"tempo\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Blocks Flushed (1h)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempo_ingester_blocks_flushed_total{job=\"tempo\"}[1h]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Flushes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(tempo_ingester_failed_flushes_total{job=\"tempo\"}[5m]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Blocks Cleared (1h)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempo_ingester_blocks_cleared_total{job=\"tempo\"}[1h]))"
    }
   ]
  },
  {
   "title": "Flush Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_ingester_flush_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_ingester_flush_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_ingester_flush_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Pushes/sec (gateway)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{job=\"tempo\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "OTEL Distributor Spans/second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_receiver_accepted_spans{job=\"tempo\"}[$__rate_interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(tempo_receiver_refused_spans{job=\"tempo\"}[$__rate_interval]))",
     "legendFormat": "refused"
    }
   ]
  },
  {
   "title": "Push Latency (Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Push Latency (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"tempo\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  { "title": "Memcached", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Requests/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_memcache_request_duration_seconds_count{job=~\"tempo\"}[$__rate_interval])) by (status_code, method)",
     "legendFormat": "{{status_code}}-{{method}}"
    }
   ]
  },
  {
   "title": "Latency By Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(cortex_memcache_request_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".99-{{method}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(cortex_memcache_request_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".9-{{method}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(cortex_memcache_request_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".5-{{method}}"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Requests/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempodb_backend_request_duration_seconds_count{job=\"tempo\"}[$__rate_interval])) by (status_code, operation)",
     "legendFormat": "{{status_code}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Latency By Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_backend_request_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (operation, le))",
     "legendFormat": ".99-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_backend_request_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (operation, le))",
     "legendFormat": ".9-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_backend_request_duration_seconds_bucket{job=\"tempo\"}[$__rate_interval])) by (operation, le))",
     "legendFormat": ".5-{{operation}}"
    }
   ]
  },
  { "title": "Ring/Memberlist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Gossip Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gauge_memberlist_health_score{job=\"tempo\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempo_memberlist_client_cluster_node_health_score{job=\"tempo\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Member Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(tempo_memberlist_client_cluster_members_count{job=\"tempo\"})",
     "legendFormat": "min"
    },
    {
     "expr": "max(tempo_memberlist_client_cluster_members_count{job=\"tempo\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "KV Store Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(tempo_memberlist_client_kv_store_count{job=\"tempo\"})",
     "legendFormat": "min"
    },
    {
     "expr": "max(tempo_memberlist_client_kv_store_count{job=\"tempo\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Vulture", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Vulture Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_vulture_trace_error_total{job=\"tempo\"}[$__rate_interval])) by (error) / ignoring (error) group_left sum(rate(tempo_vulture_trace_total{job=\"tempo\"}[$__rate_interval]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Average Vulture Query Errors",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tempo_vulture_trace_error_total{job=\"tempo\"}[$__rate_interval])) by (error) / ignoring (error) group_left sum(rate(tempo_vulture_trace_total{job=\"tempo\"}[$__rate_interval]))",
     "legendFormat": "{{secondsago}}"
    }
   ]
  },
  { "title": "Compactor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Objects Combined / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_objects_combined_total{job=\"tempo\"}[$__rate_interval])) by (level)"
    }
   ]
  },
  {
   "title": "Objects Written / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_objects_written_total{job=\"tempo\"}[$__rate_interval])) by (level)"
    }
   ]
  },
  {
   "title": "Bytes Written / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_bytes_written_total{job=\"tempo\"}[$__rate_interval])) by (level)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Compacted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempodb_compaction_blocks_total{job=\"tempo\"}[5m])) by (level)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}