{
 "title": "Nomad [bitte]",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Nomad Job Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_status_running_value)",
     "legendFormat": "running"
    },
    {
     "expr": "sum(nomad_nomad_job_status_pending_value)",
     "legendFormat": "pending"
    },
    {
     "expr": "sum(nomad_nomad_job_status_dead_value)",
     "legendFormat": "dead"
    }
   ]
  },
  {
   "title": "Unallocated Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_disk_value",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Unallocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_memory_value",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Unallocated CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_cpu_value",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}