# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/miekg/dns";
    fetch = {
      type = "git";
      url = "https://github.com/miekg/dns";
      rev = "d70eb7b9e19e2d91e54e655209bdb262c735e6bf";
      sha256 = "11fazxaj34wh2p9ngldbk6gghpi90b1zlv20hqnmdanlrkxr7j61";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "de3da57026dec695a705c07b5db51ef7a5252239";
      sha256 = "0q14qjy8s4nr08jk324c8msyawyv2ji8s6bn19fh8bjcnjxhfic0";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "530d0810a4d02f3925b731d11fecbc6eb188b03b";
      sha256 = "0q91h15z7rdm2v5l3m7dgz57k9dgza09ijwfbdgxgx9r9ji7cgxc";
    };
  }
]
